# Generated by Django 5.0.14 on 2026-05-18 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('anno', models.DateField(blank=True, null=True)),
                ('duracion', models.PositiveIntegerField(blank=True, null=True)),
                ('pais', models.CharField(blank=True, max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('guion', models.TextField(blank=True, default='')),
                ('reparto', models.TextField(blank=True, default='')),
                ('generos', models.TextField(blank=True, default='')),
                ('sinopsis', models.TextField(blank=True, default='')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
