# Generated by Django 5.0.14 on 2026-05-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='anno',
            field=models.PositiveIntegerField(blank=True, help_text='Formato de 4 dígitos', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='duracion',
            field=models.PositiveIntegerField(blank=True, help_text='Minutos', null=True),
        ),
    ]
